@startuml

left to right direction

actor Administrador as Admin


package "Módulo Empresa" {
    usecase "Registrar Empresa" as E1
    usecase "Ver Empresas" as E2
    usecase "Editar Empresa" as E3
    usecase "Eliminar Empresa" as E4
    usecase "Filtrar Empresa" as E5
}

package "Módulo Grados" {
    usecase "Registrar Grado" as G1
    usecase "Ver Grados" as G2
    usecase "Eliminar Grado" as G3
    usecase "Editar Grado" as G4
    usecase "Filtrar Grado" as G5
}

package "Módulo Prácticas Profesionales" {
    usecase "Registrar Práctica Profesional" as PP1
    usecase "Ver Prácticas Profesionales" as PP2
    usecase "Editar Práctica Profesional" as PP4
    usecase "Filtrar Práctica Profesional" as PP5
}

package "Módulo Prácticas Solicitudes" {
    usecase "Ver Solicitudes" as UC1
    usecase "Cambiar estado de Solicitud" as UC2
    usecase "Filtrar Solicitudes" as UC3
}

package "Módulo Estadísticas" {
    usecase "Consultar Estadísticas" as ES1
}

package "Módulo Sesión" {
    usecase "Iniciar Sesión" as S1
    usecase "Cerrar Sesión" as S2
}

Admin -- E1
Admin -- E2
Admin -- E3
Admin -- E4
Admin -- E5

Admin -- G1
Admin -- G2
Admin -- G3
Admin -- G4
Admin -- G5

Admin -- PP1
Admin -- PP2
Admin -- PP4
Admin -- PP5

Admin -- UC1
Admin -- UC2
Admin -- UC3

Admin -l- ES1

Admin -r- S1
Admin -r- S2

@enduml