@startuml
left to right direction
actor Administrador

package "Módulo Empresa" {
    usecase "Listar Empresas" as UC1
    usecase "Eliminar Empresa" as UC2
    usecase "Editar Empresa" as UC3
    usecase "Registrar Empresa" as UC4
}

Administrador --> UC1
Administrador --> UC2
Administrador --> UC3
Administrador --> UC4

title Caso de Uso: Gestión de Empresas
@enduml
