@startuml
left to right direction
actor Administrador

package "Módulo Prácticas Profesionales" {
    usecase "Listar Prácticas Profesionales" as UC1
    usecase "Eliminar Práctica Profesional" as UC2
    usecase "Editar Práctica Profesional" as UC3
    usecase "Registrar Práctica Profesional" as UC4
}

Administrador --> UC1
Administrador --> UC2
Administrador --> UC3
Administrador --> UC4

title Caso de Uso: Gestión de Prácticas Profesionales
@enduml
