@startuml Modelo del dominio Ticket

title Modelo del dominio - CEMU Uneatlantico

class Practica {
    +nombrePractica
    +fechaInicio
    +fechaFin
    +horas
    +descripcion
    +nombreEmpresa
    +nombreGrado
}

class Empresa {
    +nombre
}

class Grado {
    +nombre
}

class Solicitud {
    +nombrePractica
    +nombreAlumno
    +fechaSolicitud 
}

class Administrador {
    +usuario
    +contrasena
    +correo 
}

class Alumno {
    +nombre
    +correo
    +nombreGrado 
}

Practica o-- Grado : pertenece a
Practica --> Empresa : dirigida por
Alumno --> Solicitud : realiza
Solicitud --> Practica : para la práctica
Administrador ..> Practica : permite crear
Alumno --* Grado : cursa

@enduml
